DT: float = 0.02
MOTOR_SPEED_SCALING: float = 20000
MAX_X: float = 0.09
MAX_Y: float = 0.06

FILTERING_PERIOD: int = 2

MOTOR_ERROR_SCALING: float = 1. / 10.
MOTOR_D_ERROR_SCALING: float = DT / 25.
MOTOR_INTEGRAL_ERROR_SCALING: float = 1. / 5.
MAX_MOTOR_U: float = 1.

BALL_ERROR_SCALING: float = 2. / MAX_Y
BALL_D_ERROR_SCALING: float = 2. / MAX_Y
BALL_INTEGRAL_ERROR_SCALING: float = 4. / MAX_X  # 0.2 / MAX_X
BALL_MAX_INTEGRAL: float = MAX_X / 2.  # 10.

MAX_ANGLE: float = 20.
